name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            git zip unzip openjdk-17-jdk autoconf automake libtool \
            pkg-config zlib1g-dev libncurses5-dev libffi-dev \
            libssl-dev cmake

      - name: Create venv
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip==23.3.2
          pip install setuptools==69.5.1 wheel
          pip install Cython==0.29.36
          pip install buildozer==1.5.0
          pip install python-for-android==2024.01.21

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: bin/*.apk
